### ISSUE TITLE
Liquidation with votes

### ISSUE THREAD

**Issue by lajarre** [butterdao/molten#24]
As of now, voting on liquidation is too simplistic: it's based on how much the address deposited before the exchange happened.

### DAO-style

mToken implement openzeppelin ERC20Votes.

Liquidation would need to be a proper proposal using `getPastVotes` at a given block number.

The downside of this version, as is in the current naive implementation, is that it's very cheap for mToken holders to cast votes on liquidation. As there is no incentive _not to vote_ on liquidation, we could consider that all mToken holders would systematically vote for liquidation, making liquidation inevitable (this is based on the hypothesis that "a dao gov token is always better to have than an mtoken").  
Thus, the arb on discount attack would be systematic.

### ve-style

Require mToken holders to lock their mTokens to be able to vote on liquidation.

This would be very simple to implement (super simple if locking is inifinite at least).

But also, this level of friction is a good choice to prevent the arbitrage attack described above.

**Comment by vaughnmck** [comment]
There are definitely problems with the unanimous voting approach, but we agreed (rightly or wrongly) to leave it as a unanimous decision for now.

I understand that checking the addresses stored in `_deposited` is a problem. But isn't the solution to track `mToken_holders` through events and check that instead?

Perhaps you can explain what you mean by "too simplistic"?

**Comment by lajarre** [comment]
> I understand that checking the addresses stored in `_deposited` is a problem. But isn't the solution to track `mToken_holders` through events and check that instead?

Yes indeed, basically that's what ERC20Votes allows to do.

> too simplistic

I just mean that my current version with `_deposited` doesn't make sense from the mToken holder point of view. The ERC20Votes version would be fine.

I'm fine with making a ERC20Votes version for now.

**Comment by acemasterjb** [comment]
Maybe we should just remove the voting logic in favour of a lock period.

After an exchange is executed, just disallow investors from calling `claim` until the deadline is passed. I'm thinking that it's kinda pointless having to make investors vote to liquidate in addition to having a lock period.

**Comment by lajarre** [comment]
> After an exchange is executed, just disallow investors from calling claim until the deadline is passed. I'm thinking that it's kinda pointless having to make investors vote to liquidate in addition to having a lock period.

As it is implemented today it's a bit pointless. But forced liquidation is a necessary means to guarantee an option for investors/voters to terminate a representation when it's going bad. This should come at some cost to investors/voters. See the last version of the book.

**Comment by acemasterjb** [comment]
My suggestion was based on the fact that delegation is removed every time a ERC20Votes token is transferred, proportional to the amount of tokens are transferred, [see here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/ERC20Votes.sol#L200-L204).

By default (if the investor has not set a delegate the dao token beforehand) the delegation is transferred to the zero address, which is also being done on `liquidate`. In otherwards, `delegate(0x0)` is basically being called every time `claim` is called anyway, except that the delegation is removed incrementally. Transferring delegation during transfer is also the [default COMP behaviour](https://github.com/compound-finance/compound-protocol/blob/master/contracts/Governance/Comp.sol#L233-L242) as well.

This is by no means a solution that will cause a rep to be fired immediately (as it's doing in the current implementation), but it does reduce complexity, saves investors gas, and still leads to the same outcome if all investors deem the rep as gone bad (which needs to happen in the current implementation anyway, since it requires a unanimous vote).

**Comment by lajarre** [comment]
Closing this as not useful anymore, as we shelve MoltenFunding.

My closing remark: any form of liquidation needs friction (cost) from token holders, to provide security around how token holders-bound rewards are distributed (no arbitrage) and to provide guarantees to delegates so they can do their work and not expect that all delegation might vanish at any moment. For that, tools are punishment (lack of rewards or stake slash) and time locking.
