### ISSUE TITLE
Make claims automated

### ISSUE THREAD

**Issue by lajarre** [butterdao/molten#5]
How?

**Comment by acemasterjb** [comment]
This can be done once the quorum for liquidation is achieved by utilising a for loop that calls `moltenFundraiser.claim(address account)` for every account given within `liquidate`.

Or a push-pull pattern can be utilised where `liquidate` is called first and then `executeLiquidation` is called after by an authorised signer. This can also be queued and timelocked if desired.

I guess one caveat is that an array would need to be kept and maintained (for when `refund` is called). Otherwise a list of accounts would need to be provided from off-chain/front-end.

**Comment by lajarre** [comment]
> I guess one caveat is that an array would need to be kept and maintained (for when refund is called).

I've discarded for now any on-chain solution for sending tokens (mtokens or gov tokens) to all addresses at once. Time complexity and thus gas costs are unbounded, as number of token holders is unbounded.

Thus, `liquidate()` as it is now is sufficient.  
Let's consider `claim(someAddress)` for example: this would need to be triggered by an agent. An agent would only do it for its own interest:

- Either because the agent is the (soon-to-be) token holder itself: this is the status quo.
- Either because the agent does it for another reward. Thus, some reward stake could be deposited by investors.

For now the second solution is not worth digging and the first solution is amply sufficient. Let's put this on hold.
